# Generated by Django 5.1.5 on 2025-03-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('cap', models.IntegerField()),
                ('resp', models.CharField(max_length=255)),
                ('per', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('I', 'Integral')], default='M', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CAI', 'Aprendizagem'), ('CT', 'Técnico'), ('CS', 'Superior'), ('FIC', 'Formação')], default='CT', max_length=20)),
                ('ha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=100)),
                ('disc', models.CharField(max_length=100)),
                ('ch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=255)),
                ('turrma', models.CharField(max_length=255)),
            ],
        ),
    ]
